### ISSUE TITLE
Running your cartridge in OpenShift Origin

### ISSUE THREAD

**Issue by hindermath** [wshearn/openshift-community-cartridge-mono#6]
Do you have experience in running your Mono cartridge in the OpenSource OpenShift Origin? I have try it but receive the following error (all my Infos for a OpenShift support employee):
Im trying out OpenShift Origin. I have downloaded and run the HDD image as described in your documentation in Oracle VirtualBox (latest Version - downloaded today). My destination OS X is 10.8.4. I have tried to include the Mono cartridge from this location: https://raw.github.com/wshearn/openshift-community-cartridge-mono/master/metadata/manifest.yml
The error message I receive is:
Unable to complete the requested operation due to: Node execution failure (error getting result from node).. Reference ID: 87c48a1bd322a2615154d52a96567abd
In the OpenShift online version this Mono cartridge runs very fine. Can you help what to do that the Mono cartridge are running as well in the OpenShift Origin, your OpenSource version?! Thanx for advice.

**Comment by wshearn** [comment]
Access the shell to the Origin install and run tail -f /var/log/mcollective.log and try creating it again then paste the error it spit out in the mcollective log in a gist and link it here please.

**Comment by hindermath** [comment]
Done. My Gist for the collective.log is here: https://gist.github.com/hindermath/6383610
Hope you see at the error messages why your cartridge doesn't create an app in OpenShift Origin and you can help me. Thanx alot for your help!

**Comment by wshearn** [comment]
I do not see the error which is strange it does configure, several debug messages deconfigure. Which it should normally only deconfigure if there was an error. Some time this week I will try and look at it more.

**Comment by wshearn** [comment]
Hey,

Sorry for the delay. The first issue, is it is actually mcollective hitting the time out. It is set to 60 seconds in /etc/openshift/plugins.d/openshift-origin-msg-broker-mcollective.conf. On my system I bumped that up to 600(or 10 mins) and rebooted the VM. From there I was able to spot the next problem and that is the lovely ABI mismatch for Apache. So I will need to build a new version against the Fedora Apache.

**Comment by hindermath** [comment]
Thanx for your information. I have a look for new versions or can you tell me if the new version is available?

**Comment by wshearn** [comment]
It is not a matter of a new version or not, it is a matter of building mod_mono against fedora's apache.

**Comment by wshearn** [comment]
totally did not mean to close this >_>

**Comment by adroittech** [comment]
Hi,

I tried doing as per the manual of yours suggest but i get the following error.

ssh://556eb03fe0b8cd84b00000ae@adroittech-adroittech.rhcloud.com/~/git/adroittech.git/: System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 54.158.156.253:22
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at Sharpen.Extensions.CreateSocket(String host, Int32 port)
   at NSch.Util.CreateSocket(String host, Int32 port, Int32 timeout)

Any hint?

Regards,
Nirav
